resource_types:
  #version repo
  #uris must go in vault
resources:
  #get project repo
- name: algorithm-api-git
  type: git
  source:
    uri: https://github.com/msmele345/Algos
    branch: master
    skip_ssl_verification: true

- name: algorithms-ci-git
  #get ci repo with tasks and scripts
  type: git
  source:
    uri: https://github.com/msmele345/algorithms-ci
    branch: master
    skip_ssl_verification: true

#poc with dates
- name: resource-gist
  type: git
  source:
    branch: master
    uri: ((gist_uri))
    private_key: ((private_key))

#for the real semver repo
- name: algorithm-api-version
  type: semver
  source:
    driver: git
    file: verison
    branch: master
    uri: ((api_version_uri))
    private_key: ((private_key))


#- name: algorithm-cloud-processor-git
#  type: git
#  source:
#    uri: https://github.com/msmele345/algorithm-cloud-processor
#    branch: master
#    skip_ssl_verification: true
#
#- name: algorithm-producer-git
#  type: git
#  source:
#    uri: https://github.com/msmele345/algorithm-producer
#    branch: master
#    skip_ssl_verification: true

#names of the inputs are src starting points for paths
jobs:
  - name: build-and-test-api
    public: true
    plan:
      - get: algorithm-api-git
      - get: algorithms-ci-git
      - get: algorithm-api-version
        params: {bump: patch}
        trigger: true
      - task: build
        file: algorithms-ci-git/tasks/build/build.yml
        #output is build folder which should contain jar
        #jar can be used as input to artifact/minio task


#  - name: build-and-test-processor
#    public: true
#    plan:
#      - get: algorithm-cloud-processor-git
#      - get: algorithms-ci-git
#        trigger: true
#      - task: build
#        file: algorithms-ci-git/tasks/build/build-processor.yml
#
#
#  - name: build-and-test-producer
#    public: true
#    plan:
#      - get: algorithm-producer-git
#      - get: algorithms-ci-git
#        trigger: true
#      - task: build
#        file: algorithms-ci-git/tasks/build/build-producer.yml


  - name: bump-patch
    public: true
    plan:
      - get: resource-version
        params: {bump: minor}
      - put: resource-version
        params: {file: resource-version/version}

#groups:
#  - name: algorithm-api
#    jobs:
#      - build-and-test-api
#      - job-bump-date
#  - name: algorithm-cloud-processor
#    jobs: build-and-test-processor
#  - name: algorithm-producer
#    jobs: build-and-test-producer